### ISSUE TITLE
“Cannot find module ‘regedit’ ”

### ISSUE THREAD

**Issue by Chinalijian** [ironSource/node-regedit#23] opened 2017-05-25 10:50 UTC
Generated after the installation package, running software, prompt “Cannot find module ‘regedit’ ”，but the debug mode is no problem

**Comment by kessler** [comment] 2017-05-25 14:28
Hi, it is very hard to understand you problem based on this description. Can you please provide more details and / or some way to recreate your problem?

**Comment by kessler** [comment] 2017-05-27 13:40
#duplicate of #24

**Closed by kessler** 2017-05-27 13:40 UTC
