### ISSUE TITLE
Test fails because the string is not in the correct case

### ISSUE THREAD

**Issue by arieljannai** [ironSource/node-regedit#15] opened 2016-01-10 13:50 UTC
At least on my computer, [this test](https://github.com/ironSource/node-regedit/blob/master/test/regedit.test.js#L98) failed because the key in my registry is in uppercase - `SOFTWARE` and not `Software`

I think it will be fine to make the check case insensitive, cause either way windows doesn't care the case of the registry key - it could also be `SoFTwarE`.

**Comment by kessler** [comment] 2016-01-10 13:51
Thanks. Will update this soon

**Comment by nhz-io** [comment] 2017-05-30 18:06
Duplicate of #36

**Closed by nhz-io** 2017-05-30 18:06 UTC
Labels: duplicate
