### ISSUE TITLE
Error with large numbers in REG_DWORD and REG_QWORD

### ISSUE THREAD

**Issue by zariweyo** [ironSource/node-regedit#21] opened 2017-03-18 08:51 UTC
To solve this, please, in file regUtil.vbs replace CInt to CLng. (lines 37 and 43).

Thanks

**Comment by kessler** [comment] 2017-04-15 10:17
@zariweyo could you please provide some code that will help me recreate the problem? thanks

**Comment by juanjo75es** [comment] 2017-05-22 11:27
I updated the code like zariweyo said but still doesn't work if I use createKey and a number is large.

**Comment by juanjo75es** [comment] 2017-05-22 11:29
Code that fails (the problem is in the Attributes value):

                                                  regedit.createKey([s3], function(err) {

                                                          let valuesToPut = {};
                                                          valuesToPut[s3] = {
                                                            'FolderValueFlags': {
                                                              value: 0x28,
                                                              type: 'REG_DWORD'
                                                            },
                                                            'Attributes': {
                                                              value: 0xF080004D,  
                                                              type: 'REG_DWORD'
                                                            }
                                                          };

**Comment by kessler** [comment] 2017-05-22 23:20
@juanjo75es currently very busy... so it will take time to get to this. However, if you run into a solution in the meanwhile, please don't hesitate to send a PR

**Comment by nhz-io** [comment] 2017-05-26 21:54
`CLng` overflows at `0x80000000`. Need to use `CDb` for writing and `Long to ULong` correction workaround

**Comment by nhz-io** [comment] 2017-05-27 01:03
## REG_QWORD
* No conversion needed - `SetQWORDValue` accepts a `String`
* **writing** is limited to values below `9007199254740993` [Precision](http://www.rlmueller.net/Precision.htm)
* **reading** is unaffected by precision limit

**I dont see a way to overcome the precision limit on writing** :cry:

**Comment by nhz-io** [comment] 2017-05-29 23:51
Fixed by #25

**Closed** 2017-05-29 23:51 UTC

**Comment by juanjo75es** [comment] 2017-05-31 15:52
@kessler Well ... I solved my problem using:

```
var exec = require('child_process').exec;
exec( "reg add (...)" , function(error, stdout, stderr){});

```
But I guess it won't help you.

**Comment by kessler** [comment] 2017-05-31 21:05
@juanjo75es thanks for sharing the solution :)
